### ISSUE TITLE
save_path is not a valid checkpoint "i3d_rgb_imagenet/model.ckpt"

### ISSUE THREAD

**Issue by zlstl1** [oulutan/ActorConditionedAttentionMaps#11]
thanks for nice work, I am running the "train_multi_gpu.py" but I am getting an error

```
Traceback (most recent call last):
  File "train_multi_gpu.py", line 1408, in <module>
    main()
  File "train_multi_gpu.py", line 161, in main
    trainer.set_trainer()
  File "train_multi_gpu.py", line 191, in set_trainer
    self.set_session()
  File "train_multi_gpu.py", line 673, in set_session
    i3d.initialize_weights(sess, i3d_ckpt)
  File "/home/ubuntu/kim_test/ActorConditionedAttentionMaps/model_training/i3d.py", line 75, in initialize_weights
    rgb_saver.restore(sess, path_to_weights)
  File "/home/ubuntu/anaconda3/envs/acam_env/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: /home/ubuntu/kim_test/ActorConditionedAttentionMaps/model_training/weights/i3d_rgb_imagenet/model.ckpt
```
Where can I download i3d_rg_imagenet/model.ckpt?... thk.

**Comment by zlstl1** [comment]
I found model.ckpt

> https://github.com/deepmind/kinetics-i3d.git

 here
